/**
 * Auto-generated by `npm run gen:types`.
 *
 * Do not edit by hand. Regenerated from the live local Supabase instance after
 * `supabase db reset`. Until M1 lands the real schema, this is an empty stub
 * so the app compiles.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
