import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

interface RouteEntry {
  path: string;
  labelKey: string;
  keywords: string[];
  scope?: 'admin';
}

const ROOT_LABELS = new Map<string, Omit<RouteEntry, 'path'>>([
  ['/', { labelKey: 'nav.home', keywords: ['home', 'dashboard'] }],
  ['/profile/:sectionId?', { labelKey: 'profile.title', keywords: ['profile', 'account'] }],
  ['/documents', { labelKey: 'nav.documents', keywords: ['documents', 'waiver', 'sign'] }],
  ['/itinerary', { labelKey: 'nav.itinerary', keywords: ['itinerary', 'schedule', 'travel'] }],
  ['/agenda', { labelKey: 'nav.agenda', keywords: ['agenda', 'sessions', 'schedule'] }],
  ['/registration', { labelKey: 'nav.registration', keywords: ['registration', 'tasks'] }],
  ['/community', { labelKey: 'nav.community', keywords: ['community', 'people'] }],
  ['/community/photos', { labelKey: 'photos.screen.title', keywords: ['photos', 'memories'] }],
  ['/all-events', { labelKey: 'nav.allEvents', keywords: ['events'], scope: 'admin' }],
]);

const ADMIN_LABELS = new Map<string, Omit<RouteEntry, 'path' | 'scope'>>([
  ['/admin/about', { labelKey: 'admin.nav.about', keywords: ['admin', 'about', 'event'] }],
  ['/admin/agenda', { labelKey: 'admin.nav.agenda', keywords: ['admin', 'agenda', 'sessions'] }],
  ['/admin/feed', { labelKey: 'admin.nav.feed', keywords: ['admin', 'feed', 'announcements'] }],
  ['/admin/documents', { labelKey: 'admin.nav.documents', keywords: ['admin', 'documents'] }],
  ['/admin/stats', { labelKey: 'admin.nav.stats', keywords: ['admin', 'stats'] }],
  ['/admin/nudges', { labelKey: 'admin.nav.communication', keywords: ['admin', 'nudges'] }],
  ['/admin/reports', { labelKey: 'admin.nav.reports', keywords: ['admin', 'reports'] }],
  [
    '/admin/ground-transport',
    { labelKey: 'admin.nav.groundTransport', keywords: ['admin', 'transport', 'arrivals'] },
  ],
  ['/admin/rooms', { labelKey: 'admin.nav.roomAssignment', keywords: ['admin', 'rooms'] }],
  ['/admin/scan', { labelKey: 'admin.nav.scanQr', keywords: ['admin', 'scan', 'qr'] }],
  ['/admin/conflicts', { labelKey: 'admin.nav.conflicts', keywords: ['admin', 'conflicts'] }],
]);

function rootRoutes(): RouteEntry[] {
  const router = readFileSync(resolve('src/app/router.tsx'), 'utf8');
  const matches = router.matchAll(/path="([^"*]+)"/g);
  return Array.from(matches)
    .map((match) => match[1])
    .filter((path): path is string => Boolean(path))
    .flatMap((path) => {
      const route = ROOT_LABELS.get(path);
      return route ? [{ path: path.replace('/:sectionId?', ''), ...route }] : [];
    });
}

function adminRoutes(): RouteEntry[] {
  const admin = readFileSync(resolve('src/features/admin/AdminRoute.tsx'), 'utf8');
  const matches = admin.matchAll(/path="([^"*]+)"/g);
  return Array.from(matches)
    .map((match) => match[1])
    .filter((path): path is string => Boolean(path) && path !== 'events')
    .flatMap((path) => {
      const absolute = `/admin/${path}`;
      const route = ADMIN_LABELS.get(absolute);
      return route ? [{ path: absolute, scope: 'admin' as const, ...route }] : [];
    });
}

const routes = [...rootRoutes(), ...adminRoutes()].sort((a, b) => a.path.localeCompare(b.path));

const body = `// Generated by scripts/build-route-manifest.ts. Do not edit by hand.

export interface RouteManifestEntry {
  path: string;
  labelKey: string;
  keywords: string[];
  scope?: 'admin';
}

export const ROUTE_MANIFEST = ${JSON.stringify(routes, null, 2)} as const satisfies ReadonlyArray<RouteManifestEntry>;
`;

writeFileSync(resolve('src/app/routeManifest.generated.ts'), body);
